// from page: "Feature Names and IDs"
// https://system.na1.netsuite.com/app/help/helpcenter.nl?fid=chapter_N3247851.html

// to convert a copy/pasted list:
//  - find: (^[A-Z_]+$)\n(^.*$)
//  - replace: "$1":"$2",

var FEATURE_LIST = {
  "ACCOUNTING":"Accounting",
  "ACCOUNTINGPERIODS":"Accounting Periods",
  "ACHVEND":"ACH Vendor Payments",
  "ADVANCEDJOBS":"Project Management",
  "ADVANCEDPRINTING":"Advanced PDF/HTML Templates",
  "ADVANCEDPR​O​C​U​R​E​M​E​N​T​A​P​P​R​O​V​A​L​S":"Advanced Procurement Approvals",
  "ADVANCEDPROMOTIONS":"Advanced Promotions",
  "ADVANCEDREVENUERECOGNITION":"Advanced Revenue Management",
  "ADVANCEDSITECUST":"Advanced Site Customization",
  "ADVANCEDSITEMANAGEMENT":"Site Management Tools",
  "ADVBILLING":"Advanced Billing",
  "ADVBINSERIALLOTMGMT":"Advanced Bin/​Numbered ​Inventory ​Management",
  "ADVFORECASTING":"Advanced Forecasting",
  "ADVINVENTORYMGMT":"Advanced Inventory Management",
  "ADVPARTNERACCESS":"Advanced Partner Access",
  "ADVRECEIVING":"Advanced Receiving",
  "ADVSHIPPING":"Advanced Shipping",
  "ADVTAXENGINE":"Advanced Taxes",
  "ADVWEBREPORTS":"Advanced Web Reports",
  "ADVWEBSEARCH":"Advanced Web Search",
  "ALTERNATIVEPAYMENTS":"Alternative Payments",
  "ALTSALESADVFORECAST":"ALT_SALES Advanced Forecasting",
  "ALTSALESAMOUNT":"Alternate Sales Amount",
  "AMORTIZATION":"Amortization",
  "APPROVALROUTING":"Approval Routing",
  "ASSEMBLIES":"Assembly Items",
  "ASYNCCUSTOMER":"Asynchronous ​AfterSubmit ​Customer ​Processing",
  "ASYNCSALESORDER":"Asynchronous ​AfterSubmit ​Sales ​Order ​Processing",
  "AUTOLOCATIONASSIGNMENT":"Automatic Location Assignment",
  "AVAILABLETOPROMISE":"Available To Promise",
  "BARCODES":"Bar Coding and Item Labels",
  "BILLINGACCOUNTS":"Billing Accounts",
  "BILLINGCLASSES":"Per-Employee Billing Rates",
  "BILLINGWORKCENTER":"Billing Operations",
  "BILLPAY":"Online Bill Pay",
  "BILLSCOSTS":"Bill Costs To Customers",
  "BINMANAGEMENT":"Bin Management",
  "BLANKETPURCHASEORDERS":"Blanket Purchase Orders",
  "BOXNET":"Box Document Management",
  "CAMPAIGNASSISTANT":"Campaign Assistant",
  "CAMPAIGNSUBSCRIPTIONS":"Subscription Categories",
  "CCTRACKING":"Credit Card Payments",
  "CHARGEBASEDBILLING":"Charge-Based Billing",
  "CHECKOUTSUBDOMAIN":"Customizable Checkout Subdomains",
  "CLASSES":"Classes",
  "COMMISSIONONCUSTOMFIELDS":"Commission on Custom Fields",
  "COMMISSIONS":"Employee Commissions",
  "CONSOLPAYMENTS":"Consolidated Payments",
  "CREATESUITEBUNDLES":"Create bundles with SuiteBundler",
  "CRM":"Customer Relationship Management",
  "CRMTIME":"Time Tracking for CRM",
  "CRM_TEMPLATE_CATEGORIES":"CRM Template Categories",
  "CUSTOMCODE":"Client SuiteScript",
  "CUSTOMERACCESS":"Customer Access",
  "CUSTOMGLLINES":"Custom GL Lines",
  "CUSTOMRECORDS":"Custom Records",
  "CUSTOMSEGMENTS":"Custom Segments",
  "CUSTOMTRANSACTIONS":"Custom Transactions",
  "DEPARTMENTS":"Departments",
  "DIRECTDEPOSIT":"Direct Deposit",
  "DISTRIBUTIONRESOURCEPLANNING":"Distribution Resource Planning",
  "DOCUMENTPUBLISHING":"Document Publishing",
  "DOCUMENTS":"File Cabinet",
  "DOCUMENTSANTIVIRUS":"Antivirus Scanning on File Cabinet Files",
  "DOWNLOADITEMS":"Sell Downloadable Files",
  "DROPSHIPMENTS":"Drop Shipments & Special Orders",
  "DUPLICATES":"Duplicate Detection & Merge",
  "DYNALLOCATION":"Dynamic Allocation",
  "EBAY":"eBay Integration",
  "EFT":"Electronic Funds Transfer",
  "EMAILINTEGRATION":"Capture Email Replies",
  "EMPPERMS":"Global Permissions",
  "ENHANCEDPREMIERPAYROLL":"Enhanced Premier Payroll",
  "ESCALATIONRULES":"Automated Case Escalation",
  "ESTIMATES":"Estimates",
  "EXPENSEALLOCATION":"Expense Allocation",
  "EXPREPORTS":"Expense Reports",
  "EXTCRM":"Online Forms",
  "EXTREMELIST":"Inline Editing",
  "EXTSTORE":"External Catalog Site (WSDK)",
  "FXRATEUPDATES":"Currency Exchange Rate Integration",
  "GIFTCERTIFICATES":"Gift Certificates",
  "GLAUDITNUMBERING":"GL Audit Numbering",
  "GRIDORDERMANAGEMENT":"Grid Order Management",
  "GROSSPROFIT":"Gross Profit",
  "GROUPAVERAGECOSTING":"Group Average Costing",
  "HELPDESK":"Help Desk",
  "HISTORICALMETRICS":"Historical Metrics",
  "I18NTAXREPORTS":"International Tax Reports",
  "INBOUNDCASEEMAIL":"Email Case Capture",
  "INTERCOMPANYAUTODROPSHIP":"Automated Intercompany Drop Ship",
  "INTERCOMPANYAUTOELIMINATION":"Automated Intercompany Management",
  "INTERCOMPANYTIMEEXPENSE":"Intercompany Time and Expense",
  "INTRANET":"Intranet",
  "INVENTORY":"Inventory",
  "INVENTORYCOUNT":"Inventory Count",
  "IPADDRESSRULES":"IP Address Rules",
  "ISSUEDB":"Issue Management",
  "ITEMDEMANDPLANNING":"Demand Planning",
  "ITEMOPTIONS":"Item Options",
  "JOBCOSTING":"Job Costing and Project Budgeting",
  "JOBS":"Projects",
  "KNOWLEDGEBASE":"Knowledge Base",
  "KPIREPORTS":"KPI Scorecards",
  "LANDEDCOST":"Landed Cost",
  "LEADMANAGEMENT":"Lead Conversion",
  "LOCATIONS":"Locations",
  "LOTNUMBEREDINVENTORY":"Lot Tracking",
  "MAILMERGE":"Mail Merge",
  "MARKETING":"Marketing Automation",
  "MATRIXITEMS":"Matrix Items",
  "MFGROUTING":"Manufacturing Routing and Work Center",
  "MFGWORKINPROCESS":"Manufacturing Work In Process",
  "MOBILEPUSHNTF":"Mobile Push Notification",
  "MOSS":"EU Mini One Stop Shop",
  "MULTIBOOKMULTICURR":"Multi-Book ​Accounting ​and ​Multiple ​Currencies",
  "MULTICURRENCY":"Multiple Currencies",
  "MULTICURRENCYCUSTOMER":"Multi-Currency Customers",
  "MULTICURRENCYVENDOR":"Multi-Currency Vendors",
  "MULTILANGUAGE":"Multi-Language",
  "MULTILOCINVT":"Multi-Location Inventory",
  "MULTIPARTNER":"Multi-Partner Management",
  "MULTIPLEBUDGETS":"Multiple Budgets",
  "MULTIPLECALENDARS":"Multiple Calendars",
  "MULTISHIPTO":"Multiple Shipping Routes",
  "MULTISITE":"Multiple Web Sites",
  "MULTIVENDOR":"Multiple Vendors",
  "MULTPRICE":"Multiple Prices",
  "NETSUITEAPPROVALSWORKFLOW":"NetSuite Approvals Workflow",
  "NOTALTSALESAMOUNT":"Not ALT_SALES Amount",
  "NOTMULTIPARTNER":"Not Multipartner",
  "NOTTEAMSELLING":"Not Team Selling",
  "ONLINEORDERING":"Online Ordering",
  "OPENIDSSO":"OpenID Single Sign-on",
  "OPPORTUNITIES":"Opportunities",
  "OUTLOOKINTEGRATION_V3":"Outlook Integration",
  "PARTNERACCESS":"Partner Access",
  "PARTNERCOMMISSIONS":"Partner Commissions/Royalties",
  "PAYABLES":"A/P",
  "PAYCHECKJOURNAL":"Paycheck Journal",
  "PAYPALINTEGRATION":"PayPal Integration",
  "PAYROLL":"Payroll",
  "PAYROLLSERVICE":"Payroll Service",
  "PICKPACKSHIP":"Pick, Pack and Ship",
  "PRM":"Partner Relationship Management",
  "PROJECTTASKMANAGER":"Project Task Manager",
  "PROMOCODES":"Promotion Codes",
  "PURCHASECARDDATA":"Send Purchase Card Data",
  "PURCHASECONTRACTS":"Purchase Contracts",
  "PURCHASEORDERS":"Purchase Orders",
  "PURCHASEREQS":"Purchase Requests",
  "QUANTITYPRICING":"Quantity Pricing",
  "RECEIVABLES":"A/R",
  "REQUISITIONS":"Requisitions",
  "RESOURCEALLOCATIONAPPROVAL":"Resource Allocation Approval Workflow",
  "RESOURCEALLOCATIONCHART":"Resource Allocation Chart",
  "RESOURCEALLOCATIONS":"Resource Allocations",
  "RESOURCESKILLSETS":"Resource Skill Sets",
  "RETURNAUTHS":"Return Authorizations",
  "REVENUECOMMITMENTS":"Revenue Commitments",
  "REVENUERECOGNITION":"Revenue Recognition",
  "REVRECSALESORDERFORECASTING":"Sales Order Revenue Forecasting",
  "REVRECVSOE":"VSOE",
  "RFQ":"Request For Quote",
  "RUM":"Real User Monitoring",
  "SALESCAMPAIGNS":"Sales Campaigns",
  "SALESORDERS":"Sales Orders",
  "SAMLSSO":"SAML Single Sign-on",
  "SERIALIZEDINVENTORY":"Serialized Inventory",
  "SERVERSIDESCRIPTING":"Server SuiteScript",
  "SERVICEPRINTEDCHECKS":"Service Printed Checks and Stubs",
  "SERVICEPRINTEDW2S":"Service Printed W-2s and 1099s",
  "SFA":"Sales Force Automation",
  "SFA_AND_NOTASA":"SFA And Not ALT_SALES Amount",
  "SHIPPINGLABELS":"Shipping Label Integration",
  "SITELOCATIONALIASES":"Descriptive URLs",
  "SOFTDESCRIPTORS":"Credit Card Soft Descriptors",
  "STANDARDCOSTING":"Standard Costing",
  "STATACCOUNTING":"Statistical Accounts",
  "SUBSCRIPTIONBILLING":"Subscription Billing",
  "SUITEANALYTICSCONNECT":"SuiteAnalytics Connect",
  "SUITECOMMERCEENTERPRISE":"SuiteCommerce Advanced",
  "SUITESIGNON":"SuiteSignOn",
  "SUITESOCIAL":"SuiteSocial",
  "SUPPLYCHAINMANAGEMENT":"Supply Chain Management",
  "SUPPORT":"Customer Support and Service",
  "TABLEAU":"Tableau Workbook Export",
  "TAXAUDITFILES":"Tax Audit Files",
  "TBA":"Token-based Authentication",
  "TEAMSELLING":"Team Selling",
  "TELEPHONY":"Telephony Integration",
  "TIMETRACKING":"Time Tracking",
  "TRANDELETIONREASONCODE":"Use Deletion Reason",
  "UNITSOFMEASURE":"Multiple Units of Measure",
  "UPSELL":"Upsell Manager",
  "URLCOMPONENTALIASES":"URL Component Aliases",
  "VENDORACCESS":"Vendor Access",
  "VENDORRETURNAUTHS":"Vendor Return Authorizations",
  "WARRANTYAN​D​R​E​P​A​I​R​S​M​A​N​A​G​E​M​E​N​T":"Warranty and Repairs Management",
  "WEBAPPLICATIONS":"SuiteScript Server Pages",
  "WEBAPPLICATIONVERSIONING":"SuiteScript Server Pages Versioning",
  "WEBHOSTING":"Host HTML Files",
  "WEBSERVICESEXTERNAL":"Web Services",
  "WEBSITE":"Web Site",
  "WEBSTORE":"Web Store",
  "WITHHOLDINGTAX":"Withholding Tax",
  "WORKFLOW":"SuiteFlow",
  "WORKORDERS":"Work Orders"
}

// possible use the "N/config Module" instead

// normally, you would need to filter out functions. SuiteScript works a bit differently.

​function getKeys(object) {
  return Object.getOwnPropertyNames(object);
}

var featureKeys = getKeys(FEATURE_LIST);
var output = "";
var ctx = nlapiGetContext();

for(var k in featureKeys) {
  var key = featureKeys[k];
  var feature = FEATURE_LIST[key];
  var featureStatus = ctx.getFeature(feature);

  output += "\"" + key + "\": \"" + featureStatus + "\",\n"
}

'debug';
